In [8]:
from classes.PCD import PCD
def get_info(pc):
    try:
        print('Points: ', pc.points, pc.points.shape)   
    except:
        print('Points: ', pc.points)
    try:
        print('Intensity: ',  pc.intensity, pc.intensity.shape)
    except:
        print('Intensity: ', pc.intensity)
    try:        
        print('RGB: ', pc.rgb, pc.rgb.shape)
    except:
        print('RGB: ', pc.rgb)
    try:
        print('Index: ', pc.index, pc.index.shape)
    except:
        print('Index: ', pc.index)
    try:
        print('GPS Time: ', pc.gps_time, pc.gps_time.shape)
    except:
        print('GPS Time: ', pc.gps_time)
    try:
        print('Illuminance: ', pc.illuminance, pc.illuminance.shape)
    except:
        print('Illuminance: ', pc.illuminance)

In [9]:
pc = PCD()
pc.open('D:/lidar/data/orion/ex5_manual/1.txt')
pc.unique()
get_info(pc)

IndexError: index 2 is out of bounds for axis 0 with size 1

In [1]:
pc.save('D:/lidar/data/orion/ex5_manual/0.h5')
pc.open('D:/lidar/data/orion/ex5_manual/0.h5')
pc.unique()
get_info(pc)

NameError: name 'pc' is not defined

In [4]:
import h5py
import numpy as np

h5f = h5py.File('D:/lidar/data/orion/ex5_manual/0.h5', 'r')
np.asarray(h5f.get('points'))


array([[1., 1., 1.]])

In [12]:
h5f.get('dataset_a')

In [13]:
h5f.get('Intensity')

<HDF5 dataset "Intensity": shape (1,), type "<f8">

In [7]:
pc = PCD()
pc.open('D:/lidar/data/orion/ex5_manual/tree_0140.txt')
pc.save('D:/lidar/data/orion/ex5_manual/tree_0140.las')
# pc.open('D:/lidar/data/orion/ex5_manual/tree_0140.las')
# get_info(pc)

In [8]:
las = laspy.read('D:/lidar/data/orion/ex5_manual/tree_0140.las')  # Открываем файл LAS
las.illuminance

array([0.95339 , 0.936441, 0.95339 , ..., 0.855932, 0.877119, 0.915254],
      dtype=float32)

In [9]:
import numpy as np
np.nan_to_num(np.asarray(las.illuminance, dtype=np.int32))

array([0, 0, 0, ..., 0, 0, 0])

In [6]:
import laspy
import numpy as np

pc = PCD()
pc.open('D:/lidar/data/orion/ex5_manual/tree_0140.txt')

las = laspy.create()
header = laspy.LasHeader(point_format=3, version="1.4")
header.point_count = len(pc.points)
las = laspy.LasData(header)
las.x = pc.points[:, 0]
las.y = pc.points[:, 1]
las.z = pc .points[:, 2]
las.add_extra_dim(laspy.ExtraBytesParams(name="illuminance", type=np.float32))

las.illuminance = pc.illuminance

las.write('D:/lidar/data/orion/ex5_manual/tree_0140.las')

las = laspy.read('D:/lidar/data/orion/ex5_manual/tree_0140.las')  # Открываем файл LAS
las.illuminance
# las.add_extra_dim(laspy.ExtraBytesParams(name="illuminance", type=np.float32))


# np.nan_to_num(np.asarray(las.intensity, dtype=np.int32))

array([0.95339 , 0.936441, 0.95339 , ..., 0.855932, 0.877119, 0.915254],
      dtype=float32)

In [26]:
np.nan_to_num(np.asarray(las.illuminance, dtype=np.int32))

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
np.nan_to_num(np.asarray(las.intensity, dtype=np.int32))

In [2]:
def get_info(pc):
    try:
        print('Points: ', pc.points, pc.points.shape)   
    except:
        print('Points: ', pc.points)
    try:
        print('Intensity: ',  pc.intensity, pc.intensity.shape)
    except:
        print('Intensity: ', pc.intensity)
    try:        
        print('RGB: ', pc.rgb, pc.rgb.shape)
    except:
        print('RGB: ', pc.rgb)
    try:
        print('Index: ', pc.index, pc.index.shape)
    except:
        print('Index: ', pc.index)
    try:
        print('GPS Time: ', pc.gps_time, pc.gps_time.shape)
    except:
        print('GPS Time: ', pc.gps_time)
    try:
        print('Illuminance: ', pc.illuminance, pc.illuminance.shape)
    except:
        print('Illuminance: ', pc.illuminance)

In [24]:
pc = PCD()
pc.open_txt('D:/lidar/data/orion/ex5_manual/tree_0140.txt')
print(pc.illuminance)
pc.save_pcd('D:/lidar/data/orion/ex5_manual/tree_0140.pcd')
pc.open_pcd('D:/lidar/data/orion/ex5_manual/tree_0140.pcd')
print(pc.illuminance)

[0.95339  0.936441 0.95339  ... 0.855932 0.877119 0.915254]
None
